#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziSpeech-Package
      xcodeversion: 15.0
      artifactname: SpeziSpeech.xcresult
  packagevisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziSpeech-Package
      xcodeversion: 15.0
      resultBundle: SpeziSpeechVisionOS.xcresult
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      artifactname: SpeziSpeechVisionOS.xcresult
  ios:
    name: Build and Test iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      xcodeversion: 15.0
      artifactname: TestApp.xcresult
  ipados:
    name: Build and Test iPadOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      xcodeversion: 15.0
      resultBundle: TestAppiPadOS.xcresult
      destination: 'platform=iOS Simulator,name=iPad mini (6th generation)'
      artifactname: TestAppiPadOS.xcresult
  codeql:
    name: CodeQL
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      codeql: true
      scheme: SpeziSpeech
      xcodeversion: 15.0
    permissions:
      security-events: write
      actions: read
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, packagevisionos, ios, ipados]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziSpeech.xcresult SpeziSpeechVisionOS.xcresult TestApp.xcresult TestAppiPadOS.xcresult
